// <auto-generated />
using System;
using API.AmparoPet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.AmparoPet.Migrations
{
    [DbContext(typeof(AmparoPetContext))]
    [Migration("20240315132351_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API.AmparoPet.Models.CardVaccine", b =>
                {
                    b.Property<int>("CardVaccineID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CardVaccineID");

                    b.ToTable("CardVaccines");
                });

            modelBuilder.Entity("API.AmparoPet.Models.Carer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("FirstMidName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Carer", (string)null);
                });

            modelBuilder.Entity("API.AmparoPet.Models.Pet", b =>
                {
                    b.Property<int>("PetID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PetID");

                    b.ToTable("Pet", (string)null);
                });

            modelBuilder.Entity("API.AmparoPet.Models.Vaccine", b =>
                {
                    b.Property<int>("VaccineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaccineId"), 1L, 1);

                    b.Property<DateTime>("AdministeredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CardVaccineId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VaccineId");

                    b.HasIndex("CardVaccineId");

                    b.ToTable("Vaccine", (string)null);
                });

            modelBuilder.Entity("CarerPet", b =>
                {
                    b.Property<int>("CaregiversID")
                        .HasColumnType("int");

                    b.Property<int>("PetsPetID")
                        .HasColumnType("int");

                    b.HasKey("CaregiversID", "PetsPetID");

                    b.HasIndex("PetsPetID");

                    b.ToTable("CarerPet");
                });

            modelBuilder.Entity("API.AmparoPet.Models.Vaccine", b =>
                {
                    b.HasOne("API.AmparoPet.Models.CardVaccine", "CardVaccine")
                        .WithMany()
                        .HasForeignKey("CardVaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardVaccine");
                });

            modelBuilder.Entity("CarerPet", b =>
                {
                    b.HasOne("API.AmparoPet.Models.Carer", null)
                        .WithMany()
                        .HasForeignKey("CaregiversID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.AmparoPet.Models.Pet", null)
                        .WithMany()
                        .HasForeignKey("PetsPetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
